version: 2
updates:
  - package-ecosystem: elm
    directories:
      - "/"
      - "/review"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directories:
      - "/.github"
      - "/.github/workflows"
    schedule:
      interval: daily
    cooldown:
      default-days: 10
    open-pull-requests-limit: 10
  - package-ecosystem: nix
    cooldown:
      default-days: 10
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
